import { Inter } from 'next/font/google'
import { cn } from '@lib/lib'
import './style/globals.css'
import Navbar from '@components/Navbar/Navbar'
import Providers from '@components/provider'
import { Toaster } from '@components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DevNode a community for dev',
  description: 'Generated by nayan',
}

interface layoutProps {
  children: React.ReactNode,
  authModal: React.ReactNode
}


const RootLayout = ({
  children,
  authModal
}: layoutProps) => {

  return (
    <html lang="en" >
      <body className={cn(inter.className)}>

        {/* Navbar */}
        <Navbar />

        {/* authModal */}
        {authModal}

        <main className="bg-primary">
          <Providers>
            {children}
          </Providers>
          <Toaster />
        </main>

      </body>
    </html>
  )
}

export default RootLayout