import { Inter } from 'next/font/google'
import { cn } from '@lib/lib'
import './style/globals.css'
import Navbar from '@components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface layoutProps {
  children: React.ReactNode,
  authModal: React.ReactNode
}


const RootLayout = ({
  children,
  authModal
}: layoutProps) => {

  return (
    <html lang="en" >
      <body className={cn(inter.className)}>

        {/* Navbar */}
        <Navbar />

        {/* authModal */}
        {authModal}

        <main className="bg-primary">
          {children}
        </main>

      </body>
    </html>
  )
}

export default RootLayout